#! /bin/bash -f

## Here's what I do on pinconning
#module add gaussian/g16
#export GAUSS_SCRDIR=/home/dmullally/scratch
if command -v g16 > /dev/null 2>&1; then
 export GauBINARY="g16"
elif command -v gdv > /dev/null 2>&1; then
 export GauBINARY="gdv"
else
 echo "The tools check will not pass, because you have not setup the Gaussian environment"
 echo "Please setup either g16 or a recent gdv"
 exit
fi

# This is not needed.  The setup test should reset the permissions.  
# This is just to force the test to do the reset
chmod 000 examples/algebra2/testit.sh

# Configure usually installs into areas that most users don't have access to, 
# so create an area for the MQC installation
export MQC_InstallationDir=`pwd`/../install/lib

[ ! -d ${MQC_InstallationDir} ] && mkdir ${MQC_InstallationDir}

autoreconf --install

if [ $?LD_LIBRARY_PATH ] 
then
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MQC_InstallationDir}/lib
else
  export LD_LIBRARY_PATH=${MQC_InstallationDir}/lib
fi

echo ${LD_LIBRARY_PATH}

./configure --prefix=${MQC_InstallationDir}
make

make check
