#! /bin/csh -f

echo "The tools test will not pass unless you setup the Gaussian environment"
echo "in advance.  Either g16 or a recent gdv will work."

chmod 000 examples/algebra2/testit.sh

if ( -d ../install ) then
#   echo "../install does not need to be created"
else
   mkdir ../install
endif

autoreconf --install
#rm src/*.o src/*.mod

if ($?LD_LIBRARY_PATH ) then
  setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:`pwd`/../install/lib
else
  setenv LD_LIBRARY_PATH `pwd`/../install/lib
endif

echo ${LD_LIBRARY_PATH}

./configure --prefix=`pwd`/../install
make

make check
