AM_FCFLAGS = $(MQC_SPECIFIC_FCFLAGS)
AM_CPPFLAGS = $(MQC_CPPFLAGS)
AUTOMAKE_OPTIONS = subdir-objects
TESTS = ../algebra2/testit.sh ../fullci/testit.sh ../CreateDataList/testit.sh ../DataSummary/testit.sh
check_PROGRAMS = ../algebra2/algebra_fun ../fullci/fullci ../CreateDataList/CheckInput ../DataSummary/DataSummary
SOURCES = ../algebra2/algebra_fun.F03 ../fullci/fullci.F03 ../CreateDataList/CheckInput.F03 ../DataSummary/DataSummary.F03
___algebra2_algebra_fun_SOURCES = ../algebra2/algebra_fun.F03
___fullci_fullci_SOURCES = ../fullci/fullci.F03
___CreateDataList_CheckInput_SOURCES = ../CreateDataList/CheckInput.F03
___DataSummary_DataSummary_SOURCES = ../DataSummary/DataSummary.F03
LDADD = ../../src/libmqc.a ${MQC_LAPACK} ${MQC_BLAS}
build: ../algebra2/algebra_fun.$(OBJEXT) ../fullci/fullci.$(OBJEXT) ../CreateDataList/CheckInput.$(OBJEXT) ../DataSummary/DataSummary.$(OBJEXT)


