AM_FCFLAGS = $(MQC_SPECIFIC_FCFLAGS)
AM_CPPFLAGS = $(MQC_CPPFLAGS)
AUTOMAKE_OPTIONS = subdir-objects
TESTS = ../algebra2/testit.sh unitTest01 unitTest02
check_PROGRAMS = ../algebra2/algebra_fun unitTest01 unitTest02
SOURCES = ../algebra2/algebra_fun.F03
___algebra2_algebra_fun_SOURCES = ../algebra2/algebra_fun.F03
unitTest01_SOURCES = ../../unitTests/src/unitTest01.f03
unitTest02_SOURCES = ../../unitTests/src/unitTest02.f03
LDADD = ../../src/libmqc.a ${MQC_LAPACK} ${MQC_BLAS}
build: ../algebra2/algebra_fun.$(OBJEXT)

