AM_FCFLAGS = $(MQC_SPECIFIC_FCFLAGS)
AM_CPPFLAGS = $(MQC_CPPFLAGS)
AM_LDFLAGS = $(MQC_LDFLAGS) 
AUTOMAKE_OPTIONS = subdir-objects
#TESTS = ../algebra2/testit.sh ../fullci/testit.sh ../hartreefock/testit.sh ../diishf/testit.sh ../DataSummary/testit.sh ../PrintAllData/testit.sh ../SCFenergy/testit.sh ../WriteTest/testit.sh
#check_PROGRAMS = ../algebra2/algebra_fun ../fullci/fullci ../hartreefock/hartreefock ../diishf/diishf ../DataSummary/DataSummary ../PrintAllData/DataPrint ../SCFenergy/SCFenergy ../WriteTest/ReadWrite
#SOURCES = ../algebra2/algebra_fun.F03 ../fullci/fullci.F03 ../hartreefock/hartreefock.F03 ../diishf/diishf.F03 ../DataSummary/DataSummary.F03 ../PrintAllData/DataPrint.F03 ../SCFenergy/SCFenergy.F03 ../WriteTest/ReadWrite.F03
TESTS = ../algebra2/testit.sh ../fullci/testit.sh \
  ../hartreefock/testit.sh ../WriteTest/testit.sh \
  unitTest01 unitTest02 unitTest03 unitTest04
check_PROGRAMS = ../algebra2/algebra_fun ../fullci/fullci \
  ../hartreefock/hartreefock ../WriteTest/ReadWrite \
  unitTest01 unitTest02 unitTest03 unitTest04
SOURCES = ../algebra2/algebra_fun.F03 ../fullci/fullci.F03 ../hartreefock/hartreefock.F03 ../WriteTest/ReadWrite.F03
___algebra2_algebra_fun_SOURCES = ../algebra2/algebra_fun.F03
___fullci_fullci_SOURCES = ../fullci/fullci.F03
___hartreefock_hartreefock_SOURCES = ../hartreefock/hartreefock.F03
#___diishf_diishf_SOURCES = ../diishf/diishf.F03
#___DataSummary_DataSummarya_SOURCES = ../DataSummary/DataSummary.F03
#___PrintAllData_DataPrint_SOURCES = ../PrintAllData/DataPrint.F03
#___SCFenergy_SCFenergy_SOURCES = ../SCFenergy/SCFenergy.F03
___WriteTest_ReadWrite_SOURCES = ../WriteTest/ReadWrite.F03
unitTest01_SOURCES = ../../unitTests/src/unitTest01.f03
unitTest02_SOURCES = ../../unitTests/src/unitTest02.f03
unitTest03_SOURCES = ../../unitTests/src/unitTest03.f03
unitTest04_SOURCES = ../../unitTests/src/unitTest04.f03
LDADD = ../../src/libmqc.a ${MQC_LAPACK} ${MQC_BLAS}
#LDFLAGS = $(MQC_LDFLAGS)
#build: ../algebra2/algebra_fun.$(OBJEXT) ../fullci/fullci.$(OBJEXT) ../hartreefock/hartreefock.$(OBJEXT) ../diishf/diishf.$(OBJEXT) ../DataSummary/DataSummary.$(OBJEXT) ../PrintAllData/DataPrint.$(OBJEXT) ../SCFenergy/SCFenergy.$(OBJEXT) ../WriteTest/ReadWrite.$(OBJEXT)
build: ../algebra2/algebra_fun.$(OBJEXT) ../fullci/fullci.$(OBJEXT) ../hartreefock/hartreefock.$(OBJEXT) ../WriteTest/ReadWrite.$(OBJEXT)
