AM_FCFLAGS = $(MQC_SPECIFIC_FCFLAGS)
AM_CPPFLAGS = $(MQC_CPPFLAGS)
AUTOMAKE_OPTIONS = subdir-objects
TESTS = ../algebra2/testit.sh ../../unitTests/src/testit.sh
check_PROGRAMS = ../algebra2/algebra_fun ../../unitTests/src/unitTest_twoERIs
SOURCES = ../algebra2/algebra_fun.F03 ../../unitTests/src/unitTest_twoERIs.F03
___algebra2_algebra_fun_SOURCES = ../algebra2/algebra_fun.F03
______unitTests_src_unitTest_twoERIs_SOURCES = ../../unitTests/src/unitTest_twoERIs.F03
LDADD = ../../src/libmqc.a ${MQC_LAPACK} ${MQC_BLAS}
build: ../algebra2/algebra_fun.$(OBJEXT) ../../unitTests/src/unitTest_twoERIs.$(OBJEXT)


